### ISSUE TITLE
Allow other parameters in the hit than the "basic ones"

### ISSUE THREAD

**Issue by charli-polo** [pilau/ga-measurement-protocol#1]
As explained in the google documentation:

Sending Common Hit Types

Below are examples of how to send common hit types to Google Analytics. Besides these examples, you can mix and match various parameters to achieve new data relationships. **For example, to understand on which page an event occurred, send the pagePath parameter, p, along with event tracking parameters as described below.**

This is not currently supported by your plugin. I have adapted the code, but I won't suggest anything, as I am not a _real_ developper.

**Comment by gyrus** [comment]
I've not got the time to fully document and support this plugin, but I think it does support the above - after all, what you've quoted refers to "common hit types" - the most basic usage of the functionality the plugin's built to handle.

Read http://www.stumiller.me/implementing-google-analytics-measurement-protocol-in-php-and-wordpress/ - the syntax for this plugin is very similar. I think you need to look at how the `$info` parameter is constructed. See also the source at https://github.com/pilau/ga-measurement-protocol/blob/master/class-ga-measurement-protocol.php#L440
